"""Update links table

Revision ID: 093061337c3f
Revises: 406f32fd9fee
Create Date: 2025-03-20 20:35:41.009330

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '093061337c3f'
down_revision: Union[str, None] = '406f32fd9fee'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('links', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.add_column('links', sa.Column('clicks_count', sa.Integer(), nullable=True))
    op.add_column('links', sa.Column('last_clicked_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('links', sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('links', 'expires_at')
    op.drop_column('links', 'last_clicked_at')
    op.drop_column('links', 'clicks_count')
    op.drop_column('links', 'created_at')
    # ### end Alembic commands ###
